export const dataset = [
  {
    area: "Calamiong",
    children: 59,
    adolescents: 57,
    youngAdults: 86,
    middleAgedAdults: 21,
    adults: 50,
    seniors: 28,
  },
  {
    area: "Eastern County",
    children: 47,
    adolescents: 53,
    youngAdults: 106,
    middleAgedAdults: 41,
    adults: 54,
    seniors: 73,
  },
  {
    area: "Las Vegas",
    children: 54,
    adolescents: 56,
    youngAdults: 92,
    middleAgedAdults: 73,
    adults: 57,
    seniors: 99,
  },
  {
    area: "Maramba Banker's Village",
    children: 57,
    adolescents: 69,
    youngAdults: 92,
    middleAgedAdults: 99,
    adults: 60,
    seniors: 144,
  },
  {
    area: "Perrenians",
    children: 60,
    adolescents: 63,
    youngAdults: 103,
    middleAgedAdults: 144,
    adults: 59,
    seniors: 319,
  },
  {
    area: "Sabangan",
    children: 59,
    adolescents: 60,
    youngAdults: 105,
    middleAgedAdults: 319,
    adults: 65,
    seniors: 249,
  },
  {
    area: "San Marino Place",
    children: 65,
    adolescents: 60,
    youngAdults: 106,
    middleAgedAdults: 249,
    adults: 51,
    seniors: 131,
  },
  {
    area: "Alimango",
    children: 51,
    adolescents: 51,
    youngAdults: 95,
    middleAgedAdults: 131,
    adults: 60,
    seniors: 55,
  },
  {
    area: "Alimasag",
    children: 60,
    adolescents: 65,
    youngAdults: 97,
    middleAgedAdults: 55,
    adults: 67,
    seniors: 48,
  },
  {
    area: "Apahap",
    children: 67,
    adolescents: 64,
    youngAdults: 76,
    middleAgedAdults: 48,
    adults: 61,
    seniors: 25,
  },
  {
    area: "Ayungin",
    children: 61,
    adolescents: 70,
    youngAdults: 103,
    middleAgedAdults: 25,
    adults: 59,
    seniors: 99,
  },
  {
    area: "Bangus Avenue",
    children: 59,
    adolescents: 57,
    youngAdults: 86,
    middleAgedAdults: 21,
    adults: 50,
    seniors: 28,
  },
  {
    area: "Baracuda",
    children: 50,
    adolescents: 52,
    youngAdults: 78,
    middleAgedAdults: 28,
    adults: 47,
    seniors: 41,
  },
  {
    area: "Bisugo",
    children: 47,
    adolescents: 53,
    youngAdults: 106,
    middleAgedAdults: 41,
    adults: 54,
    seniors: 73,
  },
  {
    area: "Bonito",
    children: 54,
    adolescents: 56,
    youngAdults: 92,
    middleAgedAdults: 73,
    adults: 57,
    seniors: 99,
  },
  {
    area: "Dalagang Bukid Street",
    children: 57,
    adolescents: 69,
    youngAdults: 92,
    middleAgedAdults: 99,
    adults: 60,
    seniors: 144,
  },
  {
    area: "Dasmarinas Street",
    children: 60,
    adolescents: 63,
    youngAdults: 103,
    middleAgedAdults: 144,
    adults: 59,
    seniors: 319,
  },
  {
    area: "Don Marcelo I. Balolong Sr. Avenue",
    children: 59,
    adolescents: 60,
    youngAdults: 105,
    middleAgedAdults: 319,
    adults: 65,
    seniors: 249,
  },
  {
    area: "Don Maximo Street",
    children: 65,
    adolescents: 60,
    youngAdults: 106,
    middleAgedAdults: 249,
    adults: 51,
    seniors: 131,
  },
  {
    area: "Paras",
    children: 51,
    adolescents: 51,
    youngAdults: 95,
    middleAgedAdults: 131,
    adults: 60,
    seniors: 55,
  },
  {
    area: "Sugpo Street",
    children: 60,
    adolescents: 65,
    youngAdults: 97,
    middleAgedAdults: 55,
    adults: 67,
    seniors: 48,
  },
  {
    area: "Tanguegue",
    children: 67,
    adolescents: 64,
    youngAdults: 76,
    middleAgedAdults: 48,
    adults: 61,
    seniors: 25,
  },
  {
    area: "Tondaligan",
    children: 61,
    adolescents: 70,
    youngAdults: 103,
    middleAgedAdults: 25,
    adults: 59,
    seniors: 99,
  },
  {
    area: "Tuna",
    children: 59,
    adolescents: 57,
    youngAdults: 86,
    middleAgedAdults: 21,
    adults: 50,
    seniors: 28,
  },
];
